// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

// Import store internals
import { IStore } from "@latticexyz/store/src/IStore.sol";
import { StoreSwitch } from "@latticexyz/store/src/StoreSwitch.sol";
import { StoreCore } from "@latticexyz/store/src/StoreCore.sol";
import { Bytes } from "@latticexyz/store/src/Bytes.sol";
import { Memory } from "@latticexyz/store/src/Memory.sol";
import { SliceLib } from "@latticexyz/store/src/Slice.sol";
import { EncodeArray } from "@latticexyz/store/src/tightcoder/EncodeArray.sol";
import { FieldLayout } from "@latticexyz/store/src/FieldLayout.sol";
import { Schema } from "@latticexyz/store/src/Schema.sol";
import { EncodedLengths, EncodedLengthsLib } from "@latticexyz/store/src/EncodedLengths.sol";
import { ResourceId } from "@latticexyz/store/src/ResourceId.sol";

struct ExpenseReceiptData {
  uint256 amount;
  address playerAddress;
}

library ExpenseReceipt {
  // Hex below is the result of `WorldResourceIdLib.encode({ namespace: "app", name: "ExpenseReceipt", typeId: RESOURCE_OFFCHAIN_TABLE });`
  ResourceId constant _tableId = ResourceId.wrap(0x6f746170700000000000000000000000457870656e7365526563656970740000);

  FieldLayout constant _fieldLayout =
    FieldLayout.wrap(0x0034020020140000000000000000000000000000000000000000000000000000);

  // Hex-encoded key schema of (bytes32, uint256)
  Schema constant _keySchema = Schema.wrap(0x004002005f1f0000000000000000000000000000000000000000000000000000);
  // Hex-encoded value schema of (uint256, address)
  Schema constant _valueSchema = Schema.wrap(0x003402001f610000000000000000000000000000000000000000000000000000);

  /**
   * @notice Get the table's key field names.
   * @return keyNames An array of strings with the names of key fields.
   */
  function getKeyNames() internal pure returns (string[] memory keyNames) {
    keyNames = new string[](2);
    keyNames[0] = "savedKingdomId";
    keyNames[1] = "timestamp";
  }

  /**
   * @notice Get the table's value field names.
   * @return fieldNames An array of strings with the names of value fields.
   */
  function getFieldNames() internal pure returns (string[] memory fieldNames) {
    fieldNames = new string[](2);
    fieldNames[0] = "amount";
    fieldNames[1] = "playerAddress";
  }

  /**
   * @notice Register the table with its config.
   */
  function register() internal {
    StoreSwitch.registerTable(_tableId, _fieldLayout, _keySchema, _valueSchema, getKeyNames(), getFieldNames());
  }

  /**
   * @notice Register the table with its config.
   */
  function _register() internal {
    StoreCore.registerTable(_tableId, _fieldLayout, _keySchema, _valueSchema, getKeyNames(), getFieldNames());
  }

  /**
   * @notice Set amount.
   */
  function setAmount(bytes32 savedKingdomId, uint256 timestamp, uint256 amount) internal {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = savedKingdomId;
    _keyTuple[1] = bytes32(uint256(timestamp));

    StoreSwitch.setStaticField(_tableId, _keyTuple, 0, abi.encodePacked((amount)), _fieldLayout);
  }

  /**
   * @notice Set amount.
   */
  function _setAmount(bytes32 savedKingdomId, uint256 timestamp, uint256 amount) internal {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = savedKingdomId;
    _keyTuple[1] = bytes32(uint256(timestamp));

    StoreCore.setStaticField(_tableId, _keyTuple, 0, abi.encodePacked((amount)), _fieldLayout);
  }

  /**
   * @notice Set playerAddress.
   */
  function setPlayerAddress(bytes32 savedKingdomId, uint256 timestamp, address playerAddress) internal {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = savedKingdomId;
    _keyTuple[1] = bytes32(uint256(timestamp));

    StoreSwitch.setStaticField(_tableId, _keyTuple, 1, abi.encodePacked((playerAddress)), _fieldLayout);
  }

  /**
   * @notice Set playerAddress.
   */
  function _setPlayerAddress(bytes32 savedKingdomId, uint256 timestamp, address playerAddress) internal {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = savedKingdomId;
    _keyTuple[1] = bytes32(uint256(timestamp));

    StoreCore.setStaticField(_tableId, _keyTuple, 1, abi.encodePacked((playerAddress)), _fieldLayout);
  }

  /**
   * @notice Set the full data using individual values.
   */
  function set(bytes32 savedKingdomId, uint256 timestamp, uint256 amount, address playerAddress) internal {
    bytes memory _staticData = encodeStatic(amount, playerAddress);

    EncodedLengths _encodedLengths;
    bytes memory _dynamicData;

    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = savedKingdomId;
    _keyTuple[1] = bytes32(uint256(timestamp));

    StoreSwitch.setRecord(_tableId, _keyTuple, _staticData, _encodedLengths, _dynamicData);
  }

  /**
   * @notice Set the full data using individual values.
   */
  function _set(bytes32 savedKingdomId, uint256 timestamp, uint256 amount, address playerAddress) internal {
    bytes memory _staticData = encodeStatic(amount, playerAddress);

    EncodedLengths _encodedLengths;
    bytes memory _dynamicData;

    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = savedKingdomId;
    _keyTuple[1] = bytes32(uint256(timestamp));

    StoreCore.setRecord(_tableId, _keyTuple, _staticData, _encodedLengths, _dynamicData, _fieldLayout);
  }

  /**
   * @notice Set the full data using the data struct.
   */
  function set(bytes32 savedKingdomId, uint256 timestamp, ExpenseReceiptData memory _table) internal {
    bytes memory _staticData = encodeStatic(_table.amount, _table.playerAddress);

    EncodedLengths _encodedLengths;
    bytes memory _dynamicData;

    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = savedKingdomId;
    _keyTuple[1] = bytes32(uint256(timestamp));

    StoreSwitch.setRecord(_tableId, _keyTuple, _staticData, _encodedLengths, _dynamicData);
  }

  /**
   * @notice Set the full data using the data struct.
   */
  function _set(bytes32 savedKingdomId, uint256 timestamp, ExpenseReceiptData memory _table) internal {
    bytes memory _staticData = encodeStatic(_table.amount, _table.playerAddress);

    EncodedLengths _encodedLengths;
    bytes memory _dynamicData;

    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = savedKingdomId;
    _keyTuple[1] = bytes32(uint256(timestamp));

    StoreCore.setRecord(_tableId, _keyTuple, _staticData, _encodedLengths, _dynamicData, _fieldLayout);
  }

  /**
   * @notice Decode the tightly packed blob of static data using this table's field layout.
   */
  function decodeStatic(bytes memory _blob) internal pure returns (uint256 amount, address playerAddress) {
    amount = (uint256(Bytes.getBytes32(_blob, 0)));

    playerAddress = (address(Bytes.getBytes20(_blob, 32)));
  }

  /**
   * @notice Decode the tightly packed blobs using this table's field layout.
   * @param _staticData Tightly packed static fields.
   *
   *
   */
  function decode(
    bytes memory _staticData,
    EncodedLengths,
    bytes memory
  ) internal pure returns (ExpenseReceiptData memory _table) {
    (_table.amount, _table.playerAddress) = decodeStatic(_staticData);
  }

  /**
   * @notice Delete all data for given keys.
   */
  function deleteRecord(bytes32 savedKingdomId, uint256 timestamp) internal {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = savedKingdomId;
    _keyTuple[1] = bytes32(uint256(timestamp));

    StoreSwitch.deleteRecord(_tableId, _keyTuple);
  }

  /**
   * @notice Delete all data for given keys.
   */
  function _deleteRecord(bytes32 savedKingdomId, uint256 timestamp) internal {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = savedKingdomId;
    _keyTuple[1] = bytes32(uint256(timestamp));

    StoreCore.deleteRecord(_tableId, _keyTuple, _fieldLayout);
  }

  /**
   * @notice Tightly pack static (fixed length) data using this table's schema.
   * @return The static data, encoded into a sequence of bytes.
   */
  function encodeStatic(uint256 amount, address playerAddress) internal pure returns (bytes memory) {
    return abi.encodePacked(amount, playerAddress);
  }

  /**
   * @notice Encode all of a record's fields.
   * @return The static (fixed length) data, encoded into a sequence of bytes.
   * @return The lengths of the dynamic fields (packed into a single bytes32 value).
   * @return The dynamic (variable length) data, encoded into a sequence of bytes.
   */
  function encode(
    uint256 amount,
    address playerAddress
  ) internal pure returns (bytes memory, EncodedLengths, bytes memory) {
    bytes memory _staticData = encodeStatic(amount, playerAddress);

    EncodedLengths _encodedLengths;
    bytes memory _dynamicData;

    return (_staticData, _encodedLengths, _dynamicData);
  }

  /**
   * @notice Encode keys as a bytes32 array using this table's field layout.
   */
  function encodeKeyTuple(bytes32 savedKingdomId, uint256 timestamp) internal pure returns (bytes32[] memory) {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = savedKingdomId;
    _keyTuple[1] = bytes32(uint256(timestamp));

    return _keyTuple;
  }
}
