// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

// Import store internals
import { IStore } from "@latticexyz/store/src/IStore.sol";
import { StoreSwitch } from "@latticexyz/store/src/StoreSwitch.sol";
import { StoreCore } from "@latticexyz/store/src/StoreCore.sol";
import { Bytes } from "@latticexyz/store/src/Bytes.sol";
import { Memory } from "@latticexyz/store/src/Memory.sol";
import { SliceLib } from "@latticexyz/store/src/Slice.sol";
import { EncodeArray } from "@latticexyz/store/src/tightcoder/EncodeArray.sol";
import { FieldLayout } from "@latticexyz/store/src/FieldLayout.sol";
import { Schema } from "@latticexyz/store/src/Schema.sol";
import { EncodedLengths, EncodedLengthsLib } from "@latticexyz/store/src/EncodedLengths.sol";
import { ResourceId } from "@latticexyz/store/src/ResourceId.sol";

struct RevenueReceiptData {
  uint256 amountToKingdom;
  uint256 amountToReserve;
  address playerAddress;
  bytes32 savedKingdomId;
  uint256 timestamp;
}

library RevenueReceipt {
  // Hex below is the result of `WorldResourceIdLib.encode({ namespace: "app", name: "RevenueReceipt", typeId: RESOURCE_OFFCHAIN_TABLE });`
  ResourceId constant _tableId = ResourceId.wrap(0x6f746170700000000000000000000000526576656e7565526563656970740000);

  FieldLayout constant _fieldLayout =
    FieldLayout.wrap(0x0094050020201420200000000000000000000000000000000000000000000000);

  // Hex-encoded key schema of (bytes32)
  Schema constant _keySchema = Schema.wrap(0x002001005f000000000000000000000000000000000000000000000000000000);
  // Hex-encoded value schema of (uint256, uint256, address, bytes32, uint256)
  Schema constant _valueSchema = Schema.wrap(0x009405001f1f615f1f0000000000000000000000000000000000000000000000);

  /**
   * @notice Get the table's key field names.
   * @return keyNames An array of strings with the names of key fields.
   */
  function getKeyNames() internal pure returns (string[] memory keyNames) {
    keyNames = new string[](1);
    keyNames[0] = "id";
  }

  /**
   * @notice Get the table's value field names.
   * @return fieldNames An array of strings with the names of value fields.
   */
  function getFieldNames() internal pure returns (string[] memory fieldNames) {
    fieldNames = new string[](5);
    fieldNames[0] = "amountToKingdom";
    fieldNames[1] = "amountToReserve";
    fieldNames[2] = "playerAddress";
    fieldNames[3] = "savedKingdomId";
    fieldNames[4] = "timestamp";
  }

  /**
   * @notice Register the table with its config.
   */
  function register() internal {
    StoreSwitch.registerTable(_tableId, _fieldLayout, _keySchema, _valueSchema, getKeyNames(), getFieldNames());
  }

  /**
   * @notice Register the table with its config.
   */
  function _register() internal {
    StoreCore.registerTable(_tableId, _fieldLayout, _keySchema, _valueSchema, getKeyNames(), getFieldNames());
  }

  /**
   * @notice Set amountToKingdom.
   */
  function setAmountToKingdom(bytes32 id, uint256 amountToKingdom) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = id;

    StoreSwitch.setStaticField(_tableId, _keyTuple, 0, abi.encodePacked((amountToKingdom)), _fieldLayout);
  }

  /**
   * @notice Set amountToKingdom.
   */
  function _setAmountToKingdom(bytes32 id, uint256 amountToKingdom) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = id;

    StoreCore.setStaticField(_tableId, _keyTuple, 0, abi.encodePacked((amountToKingdom)), _fieldLayout);
  }

  /**
   * @notice Set amountToReserve.
   */
  function setAmountToReserve(bytes32 id, uint256 amountToReserve) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = id;

    StoreSwitch.setStaticField(_tableId, _keyTuple, 1, abi.encodePacked((amountToReserve)), _fieldLayout);
  }

  /**
   * @notice Set amountToReserve.
   */
  function _setAmountToReserve(bytes32 id, uint256 amountToReserve) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = id;

    StoreCore.setStaticField(_tableId, _keyTuple, 1, abi.encodePacked((amountToReserve)), _fieldLayout);
  }

  /**
   * @notice Set playerAddress.
   */
  function setPlayerAddress(bytes32 id, address playerAddress) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = id;

    StoreSwitch.setStaticField(_tableId, _keyTuple, 2, abi.encodePacked((playerAddress)), _fieldLayout);
  }

  /**
   * @notice Set playerAddress.
   */
  function _setPlayerAddress(bytes32 id, address playerAddress) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = id;

    StoreCore.setStaticField(_tableId, _keyTuple, 2, abi.encodePacked((playerAddress)), _fieldLayout);
  }

  /**
   * @notice Set savedKingdomId.
   */
  function setSavedKingdomId(bytes32 id, bytes32 savedKingdomId) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = id;

    StoreSwitch.setStaticField(_tableId, _keyTuple, 3, abi.encodePacked((savedKingdomId)), _fieldLayout);
  }

  /**
   * @notice Set savedKingdomId.
   */
  function _setSavedKingdomId(bytes32 id, bytes32 savedKingdomId) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = id;

    StoreCore.setStaticField(_tableId, _keyTuple, 3, abi.encodePacked((savedKingdomId)), _fieldLayout);
  }

  /**
   * @notice Set timestamp.
   */
  function setTimestamp(bytes32 id, uint256 timestamp) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = id;

    StoreSwitch.setStaticField(_tableId, _keyTuple, 4, abi.encodePacked((timestamp)), _fieldLayout);
  }

  /**
   * @notice Set timestamp.
   */
  function _setTimestamp(bytes32 id, uint256 timestamp) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = id;

    StoreCore.setStaticField(_tableId, _keyTuple, 4, abi.encodePacked((timestamp)), _fieldLayout);
  }

  /**
   * @notice Set the full data using individual values.
   */
  function set(
    bytes32 id,
    uint256 amountToKingdom,
    uint256 amountToReserve,
    address playerAddress,
    bytes32 savedKingdomId,
    uint256 timestamp
  ) internal {
    bytes memory _staticData = encodeStatic(amountToKingdom, amountToReserve, playerAddress, savedKingdomId, timestamp);

    EncodedLengths _encodedLengths;
    bytes memory _dynamicData;

    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = id;

    StoreSwitch.setRecord(_tableId, _keyTuple, _staticData, _encodedLengths, _dynamicData);
  }

  /**
   * @notice Set the full data using individual values.
   */
  function _set(
    bytes32 id,
    uint256 amountToKingdom,
    uint256 amountToReserve,
    address playerAddress,
    bytes32 savedKingdomId,
    uint256 timestamp
  ) internal {
    bytes memory _staticData = encodeStatic(amountToKingdom, amountToReserve, playerAddress, savedKingdomId, timestamp);

    EncodedLengths _encodedLengths;
    bytes memory _dynamicData;

    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = id;

    StoreCore.setRecord(_tableId, _keyTuple, _staticData, _encodedLengths, _dynamicData, _fieldLayout);
  }

  /**
   * @notice Set the full data using the data struct.
   */
  function set(bytes32 id, RevenueReceiptData memory _table) internal {
    bytes memory _staticData = encodeStatic(
      _table.amountToKingdom,
      _table.amountToReserve,
      _table.playerAddress,
      _table.savedKingdomId,
      _table.timestamp
    );

    EncodedLengths _encodedLengths;
    bytes memory _dynamicData;

    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = id;

    StoreSwitch.setRecord(_tableId, _keyTuple, _staticData, _encodedLengths, _dynamicData);
  }

  /**
   * @notice Set the full data using the data struct.
   */
  function _set(bytes32 id, RevenueReceiptData memory _table) internal {
    bytes memory _staticData = encodeStatic(
      _table.amountToKingdom,
      _table.amountToReserve,
      _table.playerAddress,
      _table.savedKingdomId,
      _table.timestamp
    );

    EncodedLengths _encodedLengths;
    bytes memory _dynamicData;

    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = id;

    StoreCore.setRecord(_tableId, _keyTuple, _staticData, _encodedLengths, _dynamicData, _fieldLayout);
  }

  /**
   * @notice Decode the tightly packed blob of static data using this table's field layout.
   */
  function decodeStatic(
    bytes memory _blob
  )
    internal
    pure
    returns (
      uint256 amountToKingdom,
      uint256 amountToReserve,
      address playerAddress,
      bytes32 savedKingdomId,
      uint256 timestamp
    )
  {
    amountToKingdom = (uint256(Bytes.getBytes32(_blob, 0)));

    amountToReserve = (uint256(Bytes.getBytes32(_blob, 32)));

    playerAddress = (address(Bytes.getBytes20(_blob, 64)));

    savedKingdomId = (Bytes.getBytes32(_blob, 84));

    timestamp = (uint256(Bytes.getBytes32(_blob, 116)));
  }

  /**
   * @notice Decode the tightly packed blobs using this table's field layout.
   * @param _staticData Tightly packed static fields.
   *
   *
   */
  function decode(
    bytes memory _staticData,
    EncodedLengths,
    bytes memory
  ) internal pure returns (RevenueReceiptData memory _table) {
    (
      _table.amountToKingdom,
      _table.amountToReserve,
      _table.playerAddress,
      _table.savedKingdomId,
      _table.timestamp
    ) = decodeStatic(_staticData);
  }

  /**
   * @notice Delete all data for given keys.
   */
  function deleteRecord(bytes32 id) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = id;

    StoreSwitch.deleteRecord(_tableId, _keyTuple);
  }

  /**
   * @notice Delete all data for given keys.
   */
  function _deleteRecord(bytes32 id) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = id;

    StoreCore.deleteRecord(_tableId, _keyTuple, _fieldLayout);
  }

  /**
   * @notice Tightly pack static (fixed length) data using this table's schema.
   * @return The static data, encoded into a sequence of bytes.
   */
  function encodeStatic(
    uint256 amountToKingdom,
    uint256 amountToReserve,
    address playerAddress,
    bytes32 savedKingdomId,
    uint256 timestamp
  ) internal pure returns (bytes memory) {
    return abi.encodePacked(amountToKingdom, amountToReserve, playerAddress, savedKingdomId, timestamp);
  }

  /**
   * @notice Encode all of a record's fields.
   * @return The static (fixed length) data, encoded into a sequence of bytes.
   * @return The lengths of the dynamic fields (packed into a single bytes32 value).
   * @return The dynamic (variable length) data, encoded into a sequence of bytes.
   */
  function encode(
    uint256 amountToKingdom,
    uint256 amountToReserve,
    address playerAddress,
    bytes32 savedKingdomId,
    uint256 timestamp
  ) internal pure returns (bytes memory, EncodedLengths, bytes memory) {
    bytes memory _staticData = encodeStatic(amountToKingdom, amountToReserve, playerAddress, savedKingdomId, timestamp);

    EncodedLengths _encodedLengths;
    bytes memory _dynamicData;

    return (_staticData, _encodedLengths, _dynamicData);
  }

  /**
   * @notice Encode keys as a bytes32 array using this table's field layout.
   */
  function encodeKeyTuple(bytes32 id) internal pure returns (bytes32[] memory) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = id;

    return _keyTuple;
  }
}
