// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

/**
 * @title IAdminSystem
 * @author MUD (https://mud.dev) by Lattice (https://lattice.xyz)
 * @dev This interface is automatically generated from the corresponding system contract. Do not edit manually.
 */
interface IAdminSystem {
  function app__registerTemplatePatent(
    bytes memory bytecode,
    string memory description,
    string memory name,
    string memory sourceCode
  ) external returns (bytes32 patentId);

  function app__mintUsdcToPlayer(address player, uint256 amount) external;

  function app__getSolarFarmSystemAddress() external view returns (address);

  function app__updateSolarFarmElectricityBalance(uint256 newElectricityBalance) external;

  function app__syncSolarFarmFiatBalance() external;

  function app__toggleSolarFarmRecharge() external;

  function app__updatUsdcAddress(address usdcAddress) external;

  function app__updateBuyReceiverAddress(address buyReceiverAddress) external;

  function app__updateSellEmitterAddress(address sellEmitterAddress) external;
}
