// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

/**
 * @title IAdminSystem
 * @author MUD (https://mud.dev) by Lattice (https://lattice.xyz)
 * @dev This interface is automatically generated from the corresponding system contract. Do not edit manually.
 */
interface IAdminSystem {
  function app__addSavedKingdomRow(bytes32 savedGameId, uint256 level) external returns (bool added);

  function app__addUsdcTokenAddress(address usdcTokenAddress) external;

  function app__updateSolarFarmElectricityBalance(uint256 newElectricityBalance) external;

  function app__updatePlayerCount(uint256 newPlayerCount) external;
}
