// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

/**
 * @title IPatentSystem
 * @author MUD (https://mud.dev) by Lattice (https://lattice.xyz)
 * @dev This interface is automatically generated from the corresponding system contract. Do not edit manually.
 */
interface IPatentSystem {
  function app__registerPatent(
    bytes memory bytecode,
    string memory description,
    string memory name,
    string memory sourceCode
  ) external returns (bytes32 patentId);

  function app__amendPatent(bytes32 patentId, string memory description, string memory name) external;

  function app__disclaimPatent(bytes32 patentId) external;

  function app__getContractSize(bytes memory bytecode) external returns (uint256 size);
}
