// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

/**
 * @title ISolarFarmSystem
 * @author MUD (https://mud.dev) by Lattice (https://lattice.xyz)
 * @dev This interface is automatically generated from the corresponding system contract. Do not edit manually.
 */
interface ISolarFarmSystem {
  function app__buyElectricity(uint256 electricityAmount) external;

  function app__buyElectricityThroughRelay(address receiver, uint256 usdcAmount) external;

  function app__sellElectricity(uint256 electricityAmount) external;

  function app__sellElectricityThroughRelay(uint256 electricityAmount) external;

  function app__claimRecharge() external;

  function app__grantKingdomRewards() external;
}
